name: '📖 Документация'
description: 'Предложения по доработке документации'
title: '[Doc]: '
labels: ['documentation']
body:
  - type: textarea
    id: description
    attributes:
      label: '📖 Описание предложения'
      description: 'Общее описание необходимых доработок по документации'
    validations:
      required: true

  - type: textarea
    id: problems
    attributes:
      label: 'Неучтенные кейсы документации'
      description: |
        * Нераскрытые в документации вопросы (можно ссылками на обсуждение).
        * Примеры неправильного использования
        * Прочие, желательно реальные, примеры проблем связанных с документацией

  - type: input
    id: page
    attributes:
      label: Страница/раздел
      description: Ссылка на страницу или наименование раздела
    
  - type: textarea
    id: tasks
    attributes:
      label: Доработки
      value: |
        ```[tasklist]
        ## (Какие доработки необходимы)
        - [ ] Описать то-то
        - [ ] Исправить опечатку там то
        - [ ] Дополнить примерами такой то раздел
        ```
