name: Build
on:
  workflow_call:
    inputs:
      v8_version:
        type: string
        required: true
      
      edt_version:
        type: string
        required: true
      
      artifact_name:
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    - name: install EDT
      uses: IT-Medved/onec-setup-build-env-action@develop
      with:
        type: edt
        edt_version: ${{ inputs.edt_version }}
        cache: true
      env: 
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 10
    
    - name: install Onec Platform
      uses: IT-Medved/onec-setup-build-env-action@develop
      with:
        type: onec
        onec_version: ${{ inputs.v8_version }}
        cache: false
        cache_distr: true
      env: 
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 10
        
    - name: convert configuration src
      uses: alkoleft/onec-edtcli-command-action@main
      with:
        export: true
        from: fixtures/demo-configuration
        to: export/configuration
        timeout: 5
      timeout-minutes: 10
      
    - name: convert yaxunit src
      uses: alkoleft/onec-edtcli-command-action@main
      with:
        export: true
        from: exts/yaxunit
        to: export/yaxunit
        timeout: 5
      timeout-minutes: 10
      
    - name: convert tests src
      uses: alkoleft/onec-edtcli-command-action@main
      with:
        export: true
        from: tests
        to: export/tests
        timeout: 5
      timeout-minutes: 10
      
    - name: create IB
      run: ibcmd infobase create --db-path=file-db --import=export/configuration --apply --force
      timeout-minutes: 5

    - name: import yaxunit
      run: ibcmd infobase config import --db-path=file-db --extension=YAXUNIT export/yaxunit
      timeout-minutes: 5

    - name: import tests
      run: ibcmd infobase config import --db-path=file-db --extension=tests export/tests
      timeout-minutes: 5

    - run: mkdir binary -p
    - name: save yaxunit
      run: ibcmd infobase config save --db-path=file-db --extension=YAXUNIT binary/yaxunit.cfe
      timeout-minutes: 5
      
    - name: save tests
      run: ibcmd infobase config save --db-path=file-db --extension=tests binary/tests.cfe
      timeout-minutes: 5
      
    - name: save configuration
      run: ibcmd infobase config save --db-path=file-db binary/configuration.cf
      timeout-minutes: 5
      
    - name: upload-artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: binary/*.*

