name: Build release
on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}-release
  cancel-in-progress: true

permissions:
    contents: write

jobs:
  export_to_designer:
    name: Export to designer xml
    uses: ./.github/workflows/step-export-xml.yml
    with:
      edt_version: 2023.1.2
      artifact_name: designer-src
    secrets: inherit
  
  build_artifacts:
    name: Build artifacts
    uses: ./.github/workflows/step-build-artifacts-windows.yml
    needs: export_to_designer
    with:
      v8_version: 8.3.10.2580
      engine_only: true
    secrets: inherit

  publish_artifacts:
    name: Publish draft release
    if: ${{ startsWith(github.ref, 'refs/tags/') && success() }}
    uses: ./.github/workflows/step-publish-artifacts.yml
    needs: build_artifacts
