name: Анализ в SonarQube (pull-request)

on: [pull_request_target]

jobs:
  SonarScanner:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      # https://docs.sonarqube.org/latest/analysis/pull-request/
    - name: Анализ в SonarQube (pull-request)
      if: github.event_name == 'pull_request'
      uses: alkoleft/sonar-quality-gate@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        GIT_URL: "https://api.github.com"
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_URL: https://sonar.openbsl.ru
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_REPOSITORY: bia-technologies/yaxunit
        CI_MERGE_REQUEST_IID: ${{ github.event.pull_request.number }}
        DEBUG: ${{ runner.debug }}
