name: Анализ в SonarQube (pull-request)

on: 
  - pull_request
jobs:
  SonarScanner:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Checkout PR
      uses: actions/checkout@v4
      with:
        # Для поддержки pull_request и pull_request_target
        # https://github.com/android-password-store/Android-Password-Store/pull/1247
        ref: refs/pull/${{ github.event.number }}/merge
        fetch-depth: 0

    # https://docs.sonarqube.org/latest/analysis/pull-request/
    - name: Analyze (pull-request)
      uses: 1CDevFlow/sonar-quality-gate@master
      with:
        sonarBranchPlugin: true
      env:
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        GIT_URL: "https://api.github.com"
        SONAR_URL: https://sonar.openbsl.ru
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_REPOSITORY: bia-technologies/yaxunit
        DEBUG: ${{ runner.debug }}
        GITHUB_REF: refs/pull/${{ github.event.number }}/merge
        GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}
        GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
