name: Export to designer xml
on:
  workflow_call:
    inputs:
      edt_version:
        type: string
        required: true
      
      artifact_name:
        type: string
        required: true
      
      engine_only:
        type: boolean
        required: false
        default: false
    outputs:
      yaxunit_version:
        value: ${{ jobs.export.outputs.yaxunit_version }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}-export
  cancel-in-progress: true

jobs:
  export:
    runs-on: ubuntu-latest
    outputs:
      yaxunit_version: ${{ steps.extract_version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version
      if: github.event_name == 'push'
      shell: bash
      run: echo "version=$(cat ./exts/yaxunit/src/Configuration/Configuration.mdo | grep -oP '(?<=<version>)[\d.]+')" >> $GITHUB_OUTPUT
      id: extract_version

    - name: install EDT
      uses: alkoleft/onec-setup-build-env-action@develop
      with:
        type: edt
        edt_version: ${{ inputs.edt_version }}
        cache: true
      env: 
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME }}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD }}
      timeout-minutes: 30
        
    - name: convert configuration src
      if: ${{ !inputs.engine_only }}
      uses: alkoleft/onec-edtcli-command-action@main
      with:
        export: true
        from: fixtures/demo-configuration
        to: export/configuration
        timeout: 5
      timeout-minutes: 10
      
    - name: convert yaxunit src
      uses: alkoleft/onec-edtcli-command-action@main
      with:
        export: true
        from: exts/yaxunit
        to: export/yaxunit
        timeout: 5
      timeout-minutes: 10
      
    - name: convert tests src
      if: ${{ !inputs.engine_only }}
      uses: alkoleft/onec-edtcli-command-action@main
      with:
        export: true
        from: tests
        to: export/tests
        timeout: 5
      timeout-minutes: 10
    
    - run: |
        cd export
        7za a -t7z ../export.7z ./

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: export.7z
        if-no-files-found: error
        retention-days: 1
