name: Run tests on Linux

on:
  workflow_call:
    inputs:
      artifact_name:
        type: string
        required: false
        default: build-artifacts
        
permissions:
    contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: binary
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: binary/YAxUnit.cfe
        generate_release_notes: true
        append_body: false
        token: ${{ secrets.GITHUB_TOKEN }}